In [ ]:
import numpy as np

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
ala1=np.arange(0,10)


1

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
ala=np.zeros((10,5))
print(ala)
ala.ndim

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


2

In [ ]:
arr = np.random.randint(1,10,(10))
arr

array([9, 5, 4, 7, 6, 6, 2, 3, 6, 6])

In [ ]:
arr.reshape(15,10)

array([[7, 1, 2, 9, 1, 6, 3, 6, 3, 4],
       [2, 5, 2, 1, 1, 1, 5, 4, 1, 5],
       [8, 1, 2, 7, 4, 1, 4, 1, 8, 1],
       [4, 4, 5, 1, 3, 3, 9, 6, 6, 1],
       [6, 3, 6, 3, 1, 7, 4, 9, 6, 9],
       [1, 8, 4, 9, 7, 4, 8, 9, 6, 3],
       [2, 2, 6, 3, 6, 1, 2, 9, 7, 8],
       [4, 5, 2, 8, 4, 2, 7, 6, 3, 8],
       [1, 7, 4, 1, 7, 6, 8, 4, 2, 5],
       [6, 9, 2, 9, 9, 7, 2, 8, 4, 8],
       [5, 9, 3, 8, 9, 5, 6, 6, 9, 7],
       [9, 2, 3, 6, 6, 8, 4, 4, 9, 1],
       [9, 6, 6, 6, 1, 1, 8, 3, 8, 7],
       [1, 4, 6, 2, 3, 3, 4, 4, 5, 1],
       [5, 1, 5, 8, 5, 2, 7, 1, 1, 1]])

In [ ]:
matriz= np.random.randint (1,20,10)
matriz


array([ 3,  4, 14,  3, 18, 14, 13,  6, 17, 16])

In [ ]:
matriz=matriz.reshape(2,5)
print(matriz)
matriz.ndim

[[ 3  4 14  3 18]
 [14 13  6 17 16]]


2

In [ ]:
matriz.max(0)

array([14, 13, 14, 17, 18])

In [ ]:
 matriz.argmin(1)

array([0, 2])

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([5,6])
print(b)


[5 6]


In [ ]:
b=np.expand_dims(b,axis=0)
print (b)

[[5 6]]


In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
b.T

array([[5],
       [6]])

In [ ]:
aq=np.arange(0,11)
aq

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
aqq=aq[0:6]
aqq

array([0, 1, 2, 3, 4, 5])

In [ ]:
aqq[:]=0
aqq

array([0, 0, 0, 0, 0, 0])

In [ ]:
aq

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
aq_copy=aq.copy()
print(aq_copy)

[ 0  0  0  0  0  0  6  7  8  9 10]


In [ ]:
aq_copy [:]=100
print (aq_copy)
print (aq)

[100 100 100 100 100 100 100 100 100 100 100]
[ 0  0  0  0  0  0  6  7  8  9 10]


In [ ]:
import pandas as pd


In [ ]:
df_books=pd.read_csv('/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')

In [ ]:
df_books=pd.read_csv('/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv',names=['Names', 'Authors', 'Users Rating', 'Reviews', 'Price', 'Year', 'Genre'])

In [ ]:
df_books.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
pd.read_json('/content/hpcharactersdataraw_3d934e85-dfa4-42ec-8520-fadfbecae574[1].json',typ='series')

NameError: ignored

In [ ]:
df_books[0:4]

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [ ]:
df_books[['Name','Author','Price']]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  Price  
0                    JJ Smith      8  
1                Stephen King     22  
2          Jordan B. Peterson     15  
3               George Orwell      6  
4    National Geographic Kids     12  
..                        ...    ...  
545               Jeff Kinney      8  
546               Jen Sincero      8  
547               Jen Sincero      8  
548               Jen Sincero      8  
549               Jen Sincero      8  

[550 rows x 3 columns]

In [ ]:
df_books.loc[0:4,['Name','Author']]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [ ]:
aw=df_books.loc[:,['Author']]=='JJ Smith'
print(aw)

     Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]


In [ ]:
df_books.iloc[0:3,0:3]

Name              Author  User Rating
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7
1                        11/22/63: A Novel        Stephen King          4.6
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7

In [ ]:
df_books.head(5)

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

##Drop Colums

In [ ]:
df_books.drop('Genre',axis=1)

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  
0                    JJ Smith          4.7    17350      8  2016  
1                Stephen King          4.6     2052     22  2011  
2          Jordan B. Peterson          4.7    18979     15  2018  
3               George Orwell          4.7    21424      6  2017  
4    National Geographic Kids          4.8     7665     12  2019  
..                        ...          ...      ...    ...   ...  
545               Jeff Kinney          4.9     9413      8  2019  
546               Jen Sincero          4.7    14331      8  2016  
547               Jen Sincero          4.7    14331      8  2017  
548               Jen Sincero          4.7    14331      8  2018  
549               Jen Sincero          4.7    14331      8  2019  

[550 rows x 6 columns]

In [ ]:
df_books.drop('Genre',axis=1).head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [ ]:
df_books.drop('Genre',axis=1, inplace=True)



KeyError: ignored

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Year  
0                    JJ Smith          4.7    17350  2016  
1                Stephen King          4.6     2052  2011  
2          Jordan B. Peterson          4.7    18979  2018  
3               George Orwell          4.7    21424  2017  
4    National Geographic Kids          4.8     7665  2019  
..                        ...          ...      ...   ...  
545               Jeff Kinney          4.9     9413  2019  
546               Jen Sincero          4.7    14331  2016  
547               Jen Sincero          4.7    14331  2017  
548               Jen Sincero          4.7    14331  2018  
549               Jen Sincero          4.7    14331  2019  

[550 rows x 5 columns]

In [ ]:
df_bookie=df_books.drop('Year',axis=1)

In [ ]:
df_books.drop([2],axis=1).head(5)

KeyError: ignored

In [ ]:
df_books.head(3)

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   

   Reviews  Year  
0    17350  2016  
1     2052  2011  
2    18979  2018

In [ ]:
df_books.drop(range(0,10),axis=0).head(5)

Name             Author  \
10                          A Man Called Ove: A Novel    Fredrik Backman   
11  A Patriot's History of the United States: From...   Larry Schweikart   
12                            A Stolen Life: A Memoir      Jaycee Dugard   
13                   A Wrinkle in Time (Time Quintet)  Madeleine L'Engle   
14  Act Like a Lady, Think Like a Man: What Men Re...       Steve Harvey   

    User Rating  Reviews  Year  
10          4.6    23848  2017  
11          4.6      460  2010  
12          4.6     4149  2011  
13          4.5     5153  2018  
14          4.6     5013  2009

##Add columns

In [ ]:
df_books.head(5)

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Year  
0                  JJ Smith          4.7    17350  2016  
1              Stephen King          4.6     2052  2011  
2        Jordan B. Peterson          4.7    18979  2018  
3             George Orwell          4.7    21424  2017  
4  National Geographic Kids          4.8     7665  2019

In [ ]:
import numpy as np

In [ ]:
df_books['Nueva_columna']=np.nan

In [ ]:
df_books.shape[0]

550

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Year  Nueva_columna  
0                    JJ Smith          4.7    17350  2016            NaN  
1                Stephen King          4.6     2052  2011            NaN  
2          Jordan B. Peterson          4.7    18979  2018            NaN  
3               George Orwell          4.7    21424  2017            NaN  
4    National Geographic Kids          4.8     7665  2019            NaN  
..                        ...          ...      ...   ...            ...  
545               Jeff Kinney          4.9     9413  2019            NaN  
546               Jen Sincero          4.7    14331  2016            NaN  
547               Jen Sincero          4.7    14331  2017            NaN  
548               Jen Sincero          4.7    14331  2018            NaN  
549               Jen Sincero          4.7    14331  2019            NaN  

[550 rows x 6 columns]

In [ ]:
Data=np.arange(0,df_books.shape[0])
Data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
df_books['Rango']=Data
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Nueva_columna  Rango  
0              NaN      0  
1              NaN      1  
2              NaN      2  
3              NaN      3  
4              NaN      4  
..             ...    ...  
545            NaN    545  
546            NaN    546  
547            NaN    547  
548            NaN    548  
549            NaN    549  

[550 rows x 9 columns]

##ADD ROWS

In [ ]:
df_books.append(df_books)

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Nueva_columna  Rango  
0              NaN      0  
1              NaN      1  
2              NaN      2  
3              NaN      3  
4              NaN      4  
..             ...    ...  
545            NaN    545  
546            NaN    546  
547            NaN    547  
548            NaN    548  
549            NaN    549  

[1100 rows x 9 columns]

In [ ]:
df_book2016=df_books['Year']>2016
df_books[df_book2016]

Name  \
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
7                       A Gentleman in Moscow: A Novel   
8        A Higher Loyalty: Truth, Lies, and Leadership   
..                                                 ...   
544                                             Wonder   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
7                 Amor Towles          4.7    19699     15  2017      Fiction   
8                 James Comey          4.7     5983      3  2018  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
544             R. J. Palacio          4.8    21625      9  2017      Fiction   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Nueva_columna  Rango  
2              NaN      2  
3              NaN      3  
4              NaN      4  
7              NaN      7  
8              NaN      8  
..             ...    ...  
544            NaN    544  
545            NaN    545  
547            NaN    547  
548            NaN    548  
549            NaN    549  

[150 rows x 9 columns]

In [ ]:
import pandas as pd

In [ ]:
df_a=pd.read_csv('/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')

In [ ]:
df_a=pd.read_csv('/content/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')


In [ ]:
df_b=pd.DataFrame(df_a)
df_b

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
cond=df_b['Genre']=='Fiction'
cond2=df_b['Year']>2016

In [ ]:
df_b[~cond & cond2]

Name  \
2              12 Rules for Life: An Antidote to Chaos   
4    5,000 Awesome Facts (About Everything!) (Natio...   
8        A Higher Loyalty: Truth, Lies, and Leadership   
26                  Astrophysics for People in a Hurry   
32                                            Becoming   
..                                                 ...   
526                                      What Happened   
536  Whose Boat Is This Boat?: Comments That Don't ...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                               Author  User Rating  Reviews  Price  Year  \
2                  Jordan B. Peterson          4.7    18979     15  2018   
4            National Geographic Kids          4.8     7665     12  2019   
8                         James Comey          4.7     5983      3  2018   
26                Neil deGrasse Tyson          4.7     9374      9  2017   
32                     Michelle Obama          4.8    61133     11  2018   
..                                ...          ...      ...    ...   ...   
526            Hillary Rodham Clinton          4.6     5492     18  2017   
536  The Staff of The Late Show with
          4.6     6669     12  2018   
547                       Jen Sincero          4.7    14331      8  2017   
548                       Jen Sincero          4.7    14331      8  2018   
549                       Jen Sincero          4.7    14331      8  2019   

           Genre  
2    Non Fiction  
4    Non Fiction  
8    Non Fiction  
26   Non Fiction  
32   Non Fiction  
..           ...  
526  Non Fiction  
536  Non Fiction  
547  Non Fiction  
548  Non Fiction  
549  Non Fiction  

[85 rows x 7 columns]

In [ ]:
df_books.memory_usage(deep=True)

Index              128
Name             59737
Author           39212
User Rating       4400
Reviews           4400
Price             4400
Year              4400
Genre            36440
Nueva_columna     4400
Rango             4400
dtype: int64

In [ ]:
caja=df_a.groupby(['Author','Year']).agg({'Reviews':['min','max'],'User Rating':'sum'})
print(caja)


                      Reviews        User Rating
                          min    max         sum
Author           Year                           
Abraham Verghese 2010    4866   4866         4.6
                 2011    4866   4866         4.6
Adam Gasiewski   2017    3113   3113         4.4
Adam Mansbach    2011    9568   9568         4.8
Adir Levy        2019    8170   8170         4.8
...                       ...    ...         ...
Wizards RPG Team 2017   16990  16990         4.8
                 2018   16990  16990         4.8
                 2019   16990  16990         4.8
Zhi Gang Sha     2009      37     37         4.6
                 2013     220    220         4.6

[493 rows x 3 columns]


In [ ]:
df1 = pd.DataFrame({'A':['A0', 'A1', 'A2','A3'],
        'B':['B0', 'B1', 'B2','B3'],
	'C':['C0', 'C1', 'C2','C3'],
	'D':['D0', 'D1', 'D2','D3']})


df2 = pd.DataFrame({'A':['A4', 'A5', 'A6','A7'],
	'B':['B4', 'B5', 'B6','B7'],
	'C':['C4', 'C5', 'C6','C7'],
	'D':['D4', 'D5', 'D6','D7']})

In [ ]:
pd.concat([df1,df2],ignore_index=True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

##Merge

##join

In [ ]:
izq = pd.DataFrame({'A': ['A0','A1','A2'],
  'B':['B0','B1','B2']},
  index=['k0','k1','k2'])

der =pd.DataFrame({'C': ['C0','C1','C2'],
  'D':['D0','D1','D2']},
  index=['k0','k2','k3']) 

In [ ]:
caja=izq.join(der,how='inner')
print(caja)

     A   B   C   D
k0  A0  B0  C0  D0
k2  A2  B2  C1  D1
