<a href="https://colab.research.google.com/github/papibunny/Portafolio_de_proyectos/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list1=np.linspace(1,10,10,dtype='int8')
list1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [3]:
indices_cond=(list1>5) & (list1<9)
indices_cond

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [4]:
l1=(list1[indices_cond])
print(l1)

[6 7 8]


In [5]:
list1[indices_cond]=99

In [6]:
l2=list1[l1]
print (l2)

[99 99  9]
